### ISSUE TITLE
import torch (module not found error)

### ISSUE THREAD

**Issue by Mian-Muhammad-AbuBakar** [ipl-uw/AIC23_Track1_UWIPL_ETRI#14]
Hi! I have successfully installed three environments and am working on Bot-SORT, when I reach the command

pyhton3 setup.py develop

I get the following error:

(botsort_env) ........\BoT-SORT>python3 setup.py develop
Traceback (most recent call last):
  File ".........\BoT-SORT\setup.py", line 8, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by hsiangwei0903** [comment]
Seems that the PyTorch environment is not successfully installed. Please check if you have successfully install PyTorch following the BoT-SORT installation.

**Comment by Mian-Muhammad-AbuBakar** [comment]
I am trying to run the command :

python tools/run_tracking.py <root-path>

and I am getting an error in the file aic_track.py:

(botsort_env) ian_muhammad_abubakar@HP-ProBook-450-G7:/media/ian_muhammad_abubakar/Ubuntu_D/ABUBAKAR/COMSATS_UNIVERSITY/PYTHON/AiCity_Challenge_2023_Track_1/AIC23_Track1_UWIPL_ETRI-main/BoT-SORT$ python tools/run_tracking.py "/media/ian_muhammad_abubakar/Ubuntu_D/ABUBAKAR/COMSATS_UNIVERSITY/PYTHON/AiCity_Challenge_2023_Track_1/AIC23_Track1_UWIPL_ETRI-main/"

Traceback (most recent call last):
  File "tools/aic_track.py", line 278, in <module>
    main()
  File "tools/aic_track.py", line 219, in main
    scenes = os.listdir(scene_path)
FileNotFoundError: [Errno 2] No such file or directory: '/media/ian_muhammad_abubakar/Ubuntu_D/ABUBAKAR/COMSATS_UNIVERSITY/PYTHON/AiCity_Challenge_2023_Track_1/AIC23_Track1_UWIPL_ETRI-main/data/test'
2023-11-20 12:44:59.217 | INFO     | __main__:<module>:267 - clustering test set
2023-11-20 12:44:59.217 | INFO     | __main__:<module>:268 - scenes list: ['S003', 'S009', 'S014', 'S018', 'S021', 'S022']
2023-11-20 12:44:59.217 | INFO     | __main__:<module>:269 - n = 15
2023-11-20 12:44:59.217 | INFO     | __main__:<module>:270 - nms_thres = 1
2023-11-20 12:44:59.217 | INFO     | __main__:<module>:271 - demo_synthetic_only = True
2023-11-20 12:44:59.218 | INFO     | __main__:<module>:272 - threshold = [([1, 5000, 10000, 15000], 0.9), ([1, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000, 11000, 12000, 13000, 14000, 15000], 0.92), ([1, 2500, 5000, 7500, 10000, 15000], 0.96), ([1, 5000, 10000, 15000], 0.9), ([1, 2500, 5000, 7500, 10000, 12500, 15000], 0.95), ([1, 2500, 5000, 7500, 10000], 0.9)]
2023-11-20 12:45:40.958 | INFO     | __main__:<module>:278 - number of anchors 8
2023-11-20 12:45:40.958 | INFO     | __main__:<module>:279 - number of people 8
2023-11-20 12:45:40.958 | INFO     | __main__:<module>:282 - anchor 0 : number of features 12
2023-11-20 12:45:40.958 | INFO     | __main__:<module>:282 - anchor 1 : number of features 9
2023-11-20 12:45:40.959 | INFO     | __main__:<module>:282 - anchor 2 : number of features 8
2023-11-20 12:45:40.959 | INFO     | __main__:<module>:282 - anchor 3 : number of features 14
2023-11-20 12:45:40.959 | INFO     | __main__:<module>:282 - anchor 4 : number of features 13
2023-11-20 12:45:40.959 | INFO     | __main__:<module>:282 - anchor 5 : number of features 7
2023-11-20 12:45:40.959 | INFO     | __main__:<module>:282 - anchor 6 : number of features 9
2023-11-20 12:45:40.959 | INFO     | __main__:<module>:282 - anchor 7 : number of features 6
Traceback (most recent call last):
  File "tools/aic_hungarian_cluster.py", line 284, in <module>
    cams = os.listdir(os.path.join(scene_path,scene))
FileNotFoundError: [Errno 2] No such file or directory: '/media/ian_muhammad_abubakar/Ubuntu_D/ABUBAKAR/COMSATS_UNIVERSITY/PYTHON/AiCity_Challenge_2023_Track_1/AIC23_Track1_UWIPL_ETRI-main/data/test/S003'

I replaced the line for adding root_path argument as:
parser.add_argument("root_path", default="/media/ian_muhammad_abubakar/Ubuntu_D/ABUBAKAR/COMSATS_UNIVERSITY/PYTHON/AiCity_Challenge_2023_Track_1/AIC23_Track1_UWIPL_ETRI-main/", type=str)

What is the mistake I am doing?
