### ISSUE TITLE
Somthing wrong

### ISSUE THREAD

**Issue by Sasukiii** [ipl-uw/AIC23_Track1_UWIPL_ETRI#25]
First of all, after the mmpose environment is installed according to the official link given, the code will report an error when loading, prompting to replace mmcv to 1.8.0, but after replacing to 1.8.0, it will prompt to install a higher version of mmcv, which will lead to the version is never correct. This is an error when running demo/top_down_video_demo_with_track_file.py. The error is on line 11.

**Comment by Sasukiii** [comment]
Second, it seems that although the code generates the foot key point detection for the real data of S001, the relevant files of foot detection are not used when the spatiotemporal consistency is redistributed, as if the foot detection part does not belong to the entire system, which is inconsistent with the description in the paper.

**Comment by Sasukiii** [comment]
Hope to reply, Thank you very much!

**Comment by Sasukiii** [comment]
The Second problem has been solved ,Only the first.

**Comment by Sasukiii** [comment]
The first problem has been solved

**Comment by Mian-Muhammad-AbuBakar** [comment]
Hello! How did you resolve first issue?

**Comment by Mian-Muhammad-AbuBakar** [comment]
And Did you got the following error while training the Detector:

Traceback (most recent call last):
  File "tools/train.py", line 123, in <module>
    main()
  File "tools/train.py", line 119, in main
    runner.train()
  File "C:\ProgramData\anaconda3\envs\mmyolo\lib\site-packages\mmengine\runner\runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "C:\ProgramData\anaconda3\envs\mmyolo\lib\site-packages\mmengine\runner\loops.py", line 105, in run
    self.runner.val_loop.run()
  File "C:\ProgramData\anaconda3\envs\mmyolo\lib\site-packages\mmengine\runner\loops.py", line 382, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "C:\ProgramData\anaconda3\envs\mmyolo\lib\site-packages\mmengine\evaluator\evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "C:\ProgramData\anaconda3\envs\mmyolo\lib\site-packages\mmengine\evaluator\metric.py", line 133, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "C:\ProgramData\anaconda3\envs\mmyolo\lib\site-packages\mmdet\evaluation\metrics\coco_metric.py", line 423, in compute_metrics
    result_files = self.results2json(preds, outfile_prefix)
  File "C:\ProgramData\anaconda3\envs\mmyolo\lib\site-packages\mmdet\evaluation\metrics\coco_metric.py", line 243, in results2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range

If yes, how you resolved it?
